// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/provision/linode.go

// Package mock is a generated GoMock package.
package mock

import (
	gomock "github.com/golang/mock/gomock"
	linodego "github.com/linode/linodego"
	reflect "reflect"
)

// MockLinodeInterface is a mock of LinodeInterface interface
type MockLinodeInterface struct {
	ctrl     *gomock.Controller
	recorder *MockLinodeInterfaceMockRecorder
}

// MockLinodeInterfaceMockRecorder is the mock recorder for MockLinodeInterface
type MockLinodeInterfaceMockRecorder struct {
	mock *MockLinodeInterface
}

// NewMockLinodeInterface creates a new mock instance
func NewMockLinodeInterface(ctrl *gomock.Controller) *MockLinodeInterface {
	mock := &MockLinodeInterface{ctrl: ctrl}
	mock.recorder = &MockLinodeInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockLinodeInterface) EXPECT() *MockLinodeInterfaceMockRecorder {
	return m.recorder
}

// CreateStackscript mocks base method
func (m *MockLinodeInterface) CreateStackscript(createOpts linodego.StackscriptCreateOptions) (*linodego.Stackscript, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateStackscript", createOpts)
	ret0, _ := ret[0].(*linodego.Stackscript)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateStackscript indicates an expected call of CreateStackscript
func (mr *MockLinodeInterfaceMockRecorder) CreateStackscript(createOpts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateStackscript", reflect.TypeOf((*MockLinodeInterface)(nil).CreateStackscript), createOpts)
}

// CreateInstance mocks base method
func (m *MockLinodeInterface) CreateInstance(instance linodego.InstanceCreateOptions) (*linodego.Instance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateInstance", instance)
	ret0, _ := ret[0].(*linodego.Instance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateInstance indicates an expected call of CreateInstance
func (mr *MockLinodeInterfaceMockRecorder) CreateInstance(instance interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInstance", reflect.TypeOf((*MockLinodeInterface)(nil).CreateInstance), instance)
}

// GetInstance mocks base method
func (m *MockLinodeInterface) GetInstance(linodeID int) (*linodego.Instance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInstance", linodeID)
	ret0, _ := ret[0].(*linodego.Instance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInstance indicates an expected call of GetInstance
func (mr *MockLinodeInterfaceMockRecorder) GetInstance(linodeID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInstance", reflect.TypeOf((*MockLinodeInterface)(nil).GetInstance), linodeID)
}

// DeleteInstance mocks base method
func (m *MockLinodeInterface) DeleteInstance(linodeID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteInstance", linodeID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteInstance indicates an expected call of DeleteInstance
func (mr *MockLinodeInterfaceMockRecorder) DeleteInstance(linodeID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteInstance", reflect.TypeOf((*MockLinodeInterface)(nil).DeleteInstance), linodeID)
}

// DeleteStackscript mocks base method
func (m *MockLinodeInterface) DeleteStackscript(id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteStackscript", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteStackscript indicates an expected call of DeleteStackscript
func (mr *MockLinodeInterfaceMockRecorder) DeleteStackscript(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteStackscript", reflect.TypeOf((*MockLinodeInterface)(nil).DeleteStackscript), id)
}
