[[constraint]]
  name = "github.com/digitalocean/godo"
  version = "1.27.0"

[[constraint]]
  name = "github.com/morikuni/aec"
  version = "1.0.0"

[[constraint]]
  name = "github.com/packethost/packngo"
  version = "0.2.0"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.1"

[[constraint]]
  name = "github.com/scaleway/scaleway-sdk-go"
  version = "1.0.0-beta.4"

[[constraint]]
  name = "github.com/sethvargo/go-password"
  version = "0.1.3"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.5"

[[constraint]]
  name = "github.com/spf13/pflag"
  version = "1.0.5"

[[constraint]]
  branch = "master"
  name = "golang.org/x/oauth2"

[[constraint]]
  name = "github.com/alexellis/go-execute"
  version = "0.2.1"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "google.golang.org/api"
  version = "0.14.0"

[[override]]
  name = "golang.org/x/sys"
  branch = "master"
  